### ISSUE TITLE
About "reconstruction image"

### ISSUE THREAD

**Issue by cwpl** [bdsaglam/torch-scae#11]
Hello, How can I get the reconstructed image？Thank you

**Comment by bdsaglam** [comment]
Reconstructions are logged to tensorboard. Check out [here](https://github.com/bdsaglam/torch-scae/blob/f271386c183bb04c1bc7c464bc2405ed4946af8e/torch_scae_experiments/base_experiment.py#L153-L164) to see how they're created.
