### ISSUE TITLE
cannot run it

### ISSUE THREAD

**Issue by soudabe1** [bdsaglam/torch-scae#7]
Hello,

When running the code, I get the following error:

--> 269     trainer = Trainer(**training_params)
    270     trainer.fit(model)
    271 

TypeError: __init__() got an unexpected keyword argument 'data_dir'

I am not sure, why I am getting this error. Would you please help with it.

**Comment by bdsaglam** [comment]
Hi,
Thanks for reporting the bug. It was related with the version of a required package. I have fixed it now.
