### ISSUE TITLE
After i trained this mode, how to use it?

### ISSUE THREAD

**Issue by Crescentz** [bdsaglam/torch-scae#8]
After i train this mode, how to use it?

**Comment by bdsaglam** [comment]
The checkpoints are saved at lightning_logs folder, you can load the experiment and then get the model.

```python
from torch_scae_experiments.mnist.train import SCAEMNIST

# load the checkpoint file at ./lightning_logs/version_0/checkpoints/
# change the version number and epoch number accordingly
experiment = SCAEMNIST.load_from_checkpoint("/path/to/lightning_logs/version_0/checkpoints/epoch=0.ckpt")
model = experiment.scae
```

It uses PyTorch Lightning library, you can check the docs for further details. 
https://pytorch-lightning.readthedocs.io/en/latest/weights_loading.html
